### PR TITLE
Fix missing parenthesis and add dev dependencies for running tests

### PR DESCRIPTION
**Pull request by nickpeihl**
I'm really excited about this idea! Would love to help more if you want someone to bounce ideas off.

### CODE REVIEW

**Comment by noffle** [comment]
Thank you nick! :pray:   Are you at sudo this week? We could chat at js night this thurs!

**Comment by nickpeihl** [comment]
Sadly, I don't live close enough to attend. Happy to chat electronically though.

**Comment by noffle** [comment]
@nickpeihl Sure, electronic works too. (Do you live in Oakland? Did I make that up?)

**Comment by nickpeihl** [comment]
You must have made that up. 😸 I live on an island in Puget Sound, North of Seattle and just East of Victoria BC. Thanks for the #ddem hint.

**Pull request merged**
